#!/usr/bin/env python3
"""Pick one real wallet for each exposure band, out of the built graph.

halo[X].d is X's distance to the nearest seed, so:
    0 hops  a seed
    1 hop   a halo node at d=1
    2 hops  a halo node at d=2
    3 hops  a counterparty of a d=2 node not itself in the graph
    none    an address with no counterparty in seeds or halo
"""
import json, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_halo import counterparties

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

CLEAN_CANDIDATES = [
    "0xd8da6bf26964af9d7eed9e03e53415d37aa96045",
    "0xab5801a7d398351b8be11c439e05c5b3259aec9b",
    "0x00000000219ab540356cbb839cbe05303d7705fa",
]

def main():
    seeds = [r["address"].lower()
             for r in json.loads((DATA / "seeds.json").read_text())["addresses"]]
    seed_set = set(seeds)
    halo = json.loads((DATA / "halo.json").read_text())["halo"]
    services = set(json.loads((DATA / "services.json").read_text())["addresses"])

    at = lambda d: [a for a, r in halo.items() if r.get("d") == d]
    d1, d2 = at(1), at(2)
    print(f"graph: {len(seeds)} seeds, {len(d1)} at distance 1, {len(d2)} at distance 2")

    picks = {"direct": seeds[0] if seeds else "", "one": d1[0] if d1 else "",
             "two": d2[0] if d2 else "", "three": "", "clean": ""}

    for node in d2[:400]:
        cps, _ = counterparties(node)
        for other in sorted(cps, key=lambda k: -cps[k]["weight"]):
            if other in seed_set or other in halo or other in services:
                continue
            picks["three"] = other
            print(f"  3-hop wallet found via {node[:10]}...")
            break
        if picks["three"]:
            break
    if d2 and not picks["three"]:
        print(f"  scanned {min(len(d2),400)} d=2 nodes, every counterparty "
              "already in the graph")

    for c in CLEAN_CANDIDATES:
        if c in seed_set or c in halo:
            continue
        cps, _ = counterparties(c)
        if any(x in seed_set or x in halo for x in cps):
            print(f"  {c[:10]}... has exposure, skipping")
            continue
        picks["clean"] = c
        break

    labels = {"direct": "Known Lazarus address", "one": "1 hop away",
              "two": "2 hops away", "three": "3 hops away", "clean": "No exposure"}
    out = {"_comment": "Generated by scripts/pick_demo_wallets.py.",
           "wallets": [{"key": k, "label": labels[k], "address": picks[k]}
                       for k in ("direct", "one", "two", "three", "clean")]}
    (DATA / "demo_wallets.json").write_text(json.dumps(out, indent=2))

    print("\nwritten to data/demo_wallets.json")
    for w in out["wallets"]:
        print(f"  {w['label']:24} {w['address'] or '(not available yet)'}")

main()
